apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogMWgKCnJvdXRlOgogIGdyb3VwX2J5OiBbJ2FsZXJ0bmFtZSddCiAgcmVjZWl2ZXI6ICd3ZWNoYXQnCiAgZ3JvdXBfd2FpdDogMHMKICBncm91cF9pbnRlcnZhbDogMXMKICByZXBlYXRfaW50ZXJ2YWw6IDFoCgpyZWNlaXZlcnM6Ci0gbmFtZTogJ3dlY2hhdCcKICB3ZWNoYXRfY29uZmlnczoKICAtIGNvcnBfaWQ6ICcqKioqJwogICAgdG9fcGFydHk6ICcqJwogICAgYWdlbnRfaWQ6ICcqKionCiAgICBhcGlfc2VjcmV0OiAnKioqJwogICAgc2VuZF9yZXNvbHZlZDogZmFsc2UKdGVtcGxhdGVzOiAKLSAnL2V0Yy9hbGVydG1hbmFnZXIvY29uZmlnbWFwcy9hbGVydG1hbmFnZXItdGVtcC8qLnlhbWwnCmluaGliaXRfcnVsZXM6Ci0gc291cmNlX21hdGNoOgogICAgcmVhc29uOiB0ZXJtaW5hdGVkCiAgdGFyZ2V0X21hdGNoOgogICAgcmVhc29uOiB3YWl0aW5nICAKICBlcXVhbDogWydzZXZlcml0eSddCg==
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
